### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by angus-88** [jenkinsci/categorized-view-plugin#22]
Hi, Can we expect a new release any time soon, there are several issues that have been fixed recently that I would find really useful.

**Comment by ljohnston** [comment]
Last published release was over 3 years ago. Some new commits recently. New release coming?

**Comment by thommelutten** [comment]
Bump on this. Can we get a release?

**Comment by taksan** [comment]
I will work to release this

**Comment by taksan** [comment]
Release completed and published :)
