### ISSUE TITLE
Buggy-UI since Jenkins 2.249.1 (LTS)

### ISSUE THREAD

**Issue by Zohhak** [jenkinsci/categorized-view-plugin#23]
Since Jenkins 2.249.1 (LTS) the displayed groups are not shown properly anymore:
![jenkins-buggy](https://user-images.githubusercontent.com/13080507/108854793-8b9b3800-75e8-11eb-83dc-0d02ce2dc1d8.png)

**Comment by taksan** [comment]
Will look into it

**Comment by Zohhak** [comment]
Thank you for testing and releasing the adjustments. Shall i close this issue?

**Comment by taksan** [comment]
Yes, please. No problem

**Comment by Zohhak** [comment]
fixed in 1.12
