### ISSUE TITLE
Jobs are sorted by internal rather then visible name

### ISSUE THREAD

**Issue by Eccenux** [jenkinsci/categorized-view-plugin#3]
By default internal name (name of the job directory) and visible name is the same. But you can use advanced options to change what is visible (job configuration -> Advanced Project Options -> Display Name). After that in standard views "Name" column sorts by visible name (`Display Name` with `Project name` fallback).

So, the problem is that in `Categorized Jobs View` sorting is always done by `Project name` and not by the one visible for the user.

![Project name is only shown in URL](https://cloud.githubusercontent.com/assets/1045235/2779016/545af102-caf8-11e3-8230-708c7342e1a4.png)

**Comment by Zitrax** [comment]
Another +1. This makes my views look unsorted after categorizing them.

The uncategorized/default view do seem to sort on the displayed name.

**Comment by taksan** [comment]
It's now possible to specify whether you want to group by display name or job name. It's not the default behavior to keep backwards behavior intact.
