### ISSUE TITLE
Allow exclusion of jobs from icon-color selection

### ISSUE THREAD

**Issue by Igorshp** [jenkinsci/categorized-view-plugin#4]
It is alright for some jobs in a category, such as pull-request builder, to fail.
The overall group icon should exclude these jobs to prevent confusion about project health.

I think it would be nice to be able to set exclude regex for the color icon.

https://github.com/jenkinsci/categorized-view-plugin/blob/master/src/main/java/org/jenkinsci/plugins/categorizedview/GroupTopLevelItem.java#L87

Thanks

**Comment by willejs** [comment]
:+1:

**Comment by taksan** [comment]
@Igorshp Ok, I'll look into it. I think it might be a nice feature

**Comment by Igorshp** [comment]
@taksan awesome, thank you!

**Comment by nemesis13** [comment]
For my company I've written a JS snippet that follows these rules:
- if there are only grey bulbs in category -> grey
- if it's only grey and one other color -> that other color
- if colors are mixed -> yellow

I think this way you get a nice overview over a whole category's status

**Comment by taksan** [comment]
I implemented a feature to exclude jobs from affecting the category status. You can now specify a regex for that.
