### ISSUE TITLE
Minor feature requests

### ISSUE THREAD

**Issue by pjangam** [jenkinsci/categorized-view-plugin#5]
Please incorporate below features, It would be great help.

**Support to show view as all expanded on default**

- Currently on default all categories are collapsed and we need  to click on name to expand category. 

- Also please add expand all/collapse all buttons on view if possible.

**Add support to use regex on all jobs**

- Currently regex filters only works on selected job in checkbox, please add support to use filter on all jobs available so that view will be updated automatically every time we add new job with same naming convention (Regex match).

**Comment by OscarBarrett** [comment]
With regards to your last point, this feature already exists.

Look for "Use a regular expression to include jobs into the view" under Job Filters when configuring a view.
